function [T_target, T_std] = calc_Entropy_inTrial(Sigs, configs, driver_ch, receiver_ch)

    Sig_target_1 = squeeze(mean(Sigs.target(:,:,driver_ch),1));
    Sig_target_2 = squeeze(mean(Sigs.target(:,:,receiver_ch),1));
    Sig_std_1 = squeeze(mean(Sigs.standard(:,:,driver_ch),1));
    Sig_std_2 = squeeze(mean(Sigs.standard(:,:,receiver_ch),1));
            
    T_target = calc_TransferEntropy(...
               Sig_target_1, Sig_target_2, ...
               configs.lag, configs.lag, configs.fs,...
               configs.interval, configs.sig_len, configs.step);
    T_std = calc_TransferEntropy(...
            Sig_std_1, Sig_std_2, ...
            configs.lag, configs.lag, configs.fs,...
            configs.interval, configs.sig_len, configs.step);

end